model:
  _target_: seq_models.gaussian_diffusion.GaussianDiffusion

  network:
    _target_: seq_models.nets.GaussianDiffusionTransformer
    in_channels: 16
    model_channels: 512
    vocab_size: ${vocab_size}
    dropout: 0.0
    bert_config_name: "prajjwal1/bert-small"

  noise_schedule:
    _target_: seq_models.noise_schedule.GaussianDiffusionSchedule
    timesteps: 1000
    noise_schedule: "cosine"

  optimizer:
    _target_: torch.optim.AdamW
    lr: 5e-4
    # lr_scheduler: null